name: Package and Publish Extension

on:
  release:
    types: [published]

jobs:
  package-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint and format check
        run: npm run check

      - name: Build extension
        run: npm run build

      - name: Install VSCE
        run: npm install -g @vscode/vsce

      - name: Package extension
        run: vsce package --no-dependencies
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Upload VSIX to release
        uses: softprops/action-gh-release@v2
        with:
          files: ./graphql-complexity-vscode-*.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to VS Code Marketplace
        run: vsce publish --no-dependencies --packagePath ./graphql-complexity-vscode-${{ github.event.release.tag_name }}.vsix
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
